# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59af6e9c401d83f769f14978b6a4656777ed78b7afe9b5ec73a4b6ca3140e321b0bc91a51de313123ef95a5c39b8c3ca2f95a3d420eba044f027fc672e2f893e

test:
  secret_key_base: f234199ad068f6aa25f3456d860fc0cdd6662ce08db33124ff470e85e010ad71a03cec5c0ca61bdc8af6d052ebfc36f8e51d885d3601e8b0bb4c84edf0e12d57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
